version: 2

project_name: traefiktop

# Global hooks (run once before all builds)
before:
  hooks:
    # GoReleaser will automatically run rustup target add for each target

# Native Rust builds with GoReleaser
builds:
  - id: linux-amd64
    builder: rust
    binary: traefiktop
    targets:
      - x86_64-unknown-linux-gnu
    flags:
      - --release
        
  - id: linux-arm64
    builder: rust
    binary: traefiktop
    targets:
      - aarch64-unknown-linux-gnu
    flags:
      - --release
        
  - id: darwin-amd64
    builder: rust
    binary: traefiktop
    targets:
      - x86_64-apple-darwin
    flags:
      - --release
        
  - id: darwin-arm64
    builder: rust
    binary: traefiktop
    targets:
      - aarch64-apple-darwin
    flags:
      - --release
        
  - id: linux-amd64-musl
    builder: rust
    binary: traefiktop
    targets:
      - x86_64-unknown-linux-musl
    flags:
      - --release
        
  - id: linux-arm64-musl  
    builder: rust
    binary: traefiktop
    targets:
      - aarch64-unknown-linux-musl
    flags:
      - --release

# Package artifacts
archives:
  - id: standard
    builds: [linux-amd64, linux-arm64, darwin-amd64, darwin-arm64]
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

  - id: musl
    builds: [linux-amd64-musl, linux-arm64-musl]
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}-musl"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

homebrew_casks:
  - name: traefiktop
    description: A TUI for visualizing Traefik routing
    homepage: https://github.com/darksworm/traefiktop
    ids: [standard]
    binary: traefiktop
    repository:
      owner: darksworm
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/traefiktop"]
          end
    caveats: |
      To get started:
        traefiktop --help

# Release config
release:
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"

# Snapshot releases
snapshot: {}

# Changelog (GitHub, grouped)
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: "Other Changes"
      order: 999

checksum:
  name_template: "checksums.txt"

aurs:
  - name: traefiktop-bin
    description: A TUI for visualizing Traefik routing
    homepage: https://github.com/darksworm/traefiktop
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/traefiktop-bin.git
    provides: [traefiktop]
    conflicts: [traefiktop]
    skip_upload: false
    commit_msg_template: "upgpkg: {{ .ProjectName }} {{ .Version }}"
    package: |
      _binname="traefiktop"
      install -Dm755 "./${_binname}" "${pkgdir}/usr/bin/${_binname}"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/${_binname}/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/${_binname}/README.md"
      if [ -f "./CHANGELOG.md" ]; then
        install -Dm644 "./CHANGELOG.md" "${pkgdir}/usr/share/doc/${_binname}/CHANGELOG.md"
      fi
    commit_author:
      name: goreleaser
      email: bot@goreleaser.com

nix:
  - name: traefiktop
    ids: [ standard ]
    goamd64: v1
    repository:
      owner: darksworm
      name: nur-packages
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

# Docker images - create separate configs for each platform
dockers:
  - id: docker-amd64
    dockerfile: Dockerfile.prebuilt
    ids: [linux-amd64-musl]
    image_templates:
      - "ghcr.io/darksworm/traefiktop:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/darksworm/traefiktop"
      
  - id: docker-arm64
    dockerfile: Dockerfile.prebuilt
    ids: [linux-arm64-musl]
    image_templates:
      - "ghcr.io/darksworm/traefiktop:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/darksworm/traefiktop"

docker_manifests:
  - name_template: "ghcr.io/darksworm/traefiktop:{{ .Version }}"
    image_templates:
      - "ghcr.io/darksworm/traefiktop:{{ .Version }}-amd64"
      - "ghcr.io/darksworm/traefiktop:{{ .Version }}-arm64"
      
  - name_template: "ghcr.io/darksworm/traefiktop:latest"
    image_templates:
      - "ghcr.io/darksworm/traefiktop:{{ .Version }}-amd64"
      - "ghcr.io/darksworm/traefiktop:{{ .Version }}-arm64"

nfpms:
  - id: linux-packages-standard
    ids: [linux-amd64, linux-arm64]
    formats: [deb, rpm, apk]
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: "darksworm <bot@goreleaser.com>"
    homepage: "https://github.com/darksworm/traefiktop"
    description: "A TUI for visualizing Traefik routing"
    license: GPL-3.0-or-later
    section: utils
    priority: optional
    provides: [traefiktop]
    conflicts: [traefiktop, traefiktop-musl]

  - id: linux-packages-musl
    ids: [linux-amd64-musl, linux-arm64-musl]
    formats: [deb, rpm, apk]
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}-musl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: "traefiktop-musl"
    maintainer: "darksworm <bot@goreleaser.com>"
    homepage: "https://github.com/darksworm/traefiktop"
    description: "A TUI for visualizing Traefik routing (musl build)"
    license: GPL-3.0-or-later
    section: utils
    priority: optional
    provides: [traefiktop]
    conflicts: [traefiktop, traefiktop-standard]
