version: 2

project_name: argonaut

# Global hooks (run once before all builds)
before:
  hooks:
    - bun install --frozen-lockfile 
    - bun run generate:licenses
    - rm -rf dist

# Build with Bun (bun build --compile)
builds:
  - id: bun-standard
    builder: bun
    binary: argonaut
    main: src/main.tsx
    targets:
      - linux-x64-modern
      - linux-arm64
      - darwin-x64
      - darwin-arm64

  - id: bun-musl
    builder: bun
    binary: argonaut
    main: src/main.tsx
    targets:
      - linux-x64-musl-modern
      - linux-arm64-musl

# Package artifacts (use tar.gz, no deprecation warnings)
archives:
  - id: bun-archives-standard
    ids: [bun-standard]  # standard builds
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

  - id: bun-archives-musl
    ids: [bun-musl]  # musl builds
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}-musl"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

# macOS distribution via Homebrew Casks (Formulas are deprecated)
homebrew_casks:
  - name: argonaut
    description: A GitOps CLI tool for managing ArgoCD applications
    homepage: https://github.com/darksworm/argonaut
    ids: [bun-archives-standard]    # use the standard archives (macOS is not musl)
    binary: argonaut       # the binary name inside the archive
    repository:
      owner: darksworm
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    # If you don't sign/notarize, consider removing quarantine on install:
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argonaut"]
          end
    caveats: |
      To get started:
        argonaut --help

# Release config
release:
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"

# Snapshot releases
snapshot: {}

# Changelog (GitHub, grouped)
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: "Other Changes"
      order: 999

# Checksums for all artifacts
checksum:
  name_template: "checksums.txt"

aurs:
  - name: argonaut-bin
    description: A GitOps CLI tool for managing ArgoCD applications
    homepage: https://github.com/darksworm/argonaut
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/argonaut-bin.git
    provides: [argonaut]
    conflicts: [argonaut]
    skip_upload: false
    commit_msg_template: "upgpkg: {{ .ProjectName }} {{ .Version }}"
    package: |
      _binname="argonaut"
      install -Dm755 "./${_binname}" "${pkgdir}/usr/bin/argonaut"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/argonaut/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/argonaut/README.md"
      install -Dm644 "./CHANGELOG.md" "${pkgdir}/usr/share/doc/argonaut/CHANGELOG.md"
    commit_author:
      name: goreleaser
      email: bot@goreleaser.com

nix:
  - name: argonaut
    ids: [ bun-archives-standard ]
    goamd64: v1
    repository:
      owner: darksworm
      name: nur-packages
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

nfpms:
  - id: linux-packages-standard
    ids: [bun-standard]
    formats: [deb, rpm, apk]
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: "darksworm <bot@goreleaser.com>"
    homepage: "https://github.com/darksworm/argonaut"
    description: "A CLI tool for managing Argo CD applications"
    license: GPL-3.0-or-later
    section: utils
    priority: optional
    provides: [argonaut]
    conflicts: [argonaut, argonaut-musl]

  - id: linux-packages-musl
    ids: [bun-musl]
    formats: [deb, rpm, apk]
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}-musl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: "argonaut-musl"
    maintainer: "darksworm <bot@goreleaser.com>"
    homepage: "https://github.com/darksworm/argonaut"
    description: "A CLI tool for managing Argo CD applications (musl build)"
    license: GPL-3.0-or-later
    section: utils
    priority: optional
    provides: [argonaut]
    conflicts: [argonaut, argonaut-standard]