version: 2

project_name: traefiktop

# Global hooks (run once before all builds)
before:
  hooks:
    - ./tools/cross-compile.sh

# Skip builds - we use pre-compiled Rust binaries
builds:
  - skip: true

# Archive configuration for distribution
archives:
  - id: rust-archives-standard 
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-linux-amd64"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - src: target/x86_64-unknown-linux-gnu/release/traefiktop
        dst: traefiktop
        
  - id: rust-archives-linux-arm64
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-linux-arm64"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - src: target/aarch64-unknown-linux-gnu/release/traefiktop
        dst: traefiktop
        
  - id: rust-archives-darwin-amd64
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-darwin-amd64"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - src: target/x86_64-apple-darwin/release/traefiktop
        dst: traefiktop
        
  - id: rust-archives-darwin-arm64
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-darwin-arm64"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - src: target/aarch64-apple-darwin/release/traefiktop
        dst: traefiktop

  - id: rust-archives-musl-amd64
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-linux-amd64-musl"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - src: target/x86_64-unknown-linux-musl/release/traefiktop
        dst: traefiktop
        
  - id: rust-archives-musl-arm64
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-linux-arm64-musl"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - src: target/aarch64-unknown-linux-musl/release/traefiktop
        dst: traefiktop

homebrew_casks:
  - name: traefiktop
    description: A TUI for visualizing Traefik routing
    homepage: https://github.com/darksworm/traefiktop
    ids: [rust-archives-darwin-amd64, rust-archives-darwin-arm64]
    binary: traefiktop
    repository:
      owner: darksworm
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/traefiktop"]
          end
    caveats: |
      To get started:
        traefiktop --help

# Release config
release:
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"

# Snapshot releases
snapshot: {}

# Changelog (GitHub, grouped)
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: "Other Changes"
      order: 999

checksum:
  name_template: "checksums.txt"

aurs:
  - name: traefiktop-bin
    description: A TUI for visualizing Traefik routing
    homepage: https://github.com/darksworm/traefiktop
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/traefiktop-bin.git
    provides: [traefiktop]
    conflicts: [traefiktop]
    skip_upload: false
    commit_msg_template: "upgpkg: {{ .ProjectName }} {{ .Version }}"
    package: |
      _binname="traefiktop"
      install -Dm755 "./${_binname}" "${pkgdir}/usr/bin/${_binname}"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/${_binname}/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/${_binname}/README.md"
      if [ -f "./CHANGELOG.md" ]; then
        install -Dm644 "./CHANGELOG.md" "${pkgdir}/usr/share/doc/${_binname}/CHANGELOG.md"
      fi
    commit_author:
      name: goreleaser
      email: bot@goreleaser.com

nix:
  - name: traefiktop
    ids: [ rust-archives-standard, rust-archives-linux-arm64 ]
    goamd64: v1
    repository:
      owner: darksworm
      name: nur-packages
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

# Docker images (v2)
# Docker images (dockers_v2)
dockers_v2:
  - id: docker-multi
    dockerfile: Dockerfile.rust
    ids: [rust-archives-musl-amd64, rust-archives-musl-arm64]
    images:
      - ghcr.io/darksworm/traefiktop
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://github.com/darksworm/traefiktop"

nfpms:
  - id: linux-packages-standard
    ids: [rust-archives-standard, rust-archives-linux-arm64]
    formats: [deb, rpm, apk]
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: "darksworm <bot@goreleaser.com>"
    homepage: "https://github.com/darksworm/traefiktop"
    description: "A TUI for visualizing Traefik routing"
    license: GPL-3.0-or-later
    section: utils
    priority: optional
    provides: [traefiktop]
    conflicts: [traefiktop, traefiktop-musl]

  - id: linux-packages-musl
    ids: [rust-archives-musl-amd64, rust-archives-musl-arm64]
    formats: [deb, rpm, apk]
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}-musl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: "traefiktop-musl"
    maintainer: "darksworm <bot@goreleaser.com>"
    homepage: "https://github.com/darksworm/traefiktop"
    description: "A TUI for visualizing Traefik routing (musl build)"
    license: GPL-3.0-or-later
    section: utils
    priority: optional
    provides: [traefiktop]
    conflicts: [traefiktop, traefiktop-standard]
