on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

name: release-pipeline

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .release-please-config.json

  goreleaser:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.release-please.outputs.tag_name }}

      - name: Setup Git identity
        run: |
          git config --global user.name "goreleaser"
          git config --global user.email "bot@goreleaser.com"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache  
        uses: Swatinem/rust-cache@v2
        with:
          # Cache all target directories for cross-compilation
          key: rust-cache-cross-compile
          # Include Zig and cargo-zigbuild in cache key
          prefix-key: "v1-rust"
          # Cache registry and git dependencies
          cache-directories: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          # Cache all target directories
          cache-all-crates: true

      - name: Setup Zig (for GoReleaser Rust cross-compilation)
        uses: mlugg/setup-zig@v2
        with:
          version: "0.13.0"
          
      - name: Install cargo-zigbuild (for GoReleaser Rust cross-compilation)
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-zigbuild
          
      - name: Cache cargo-zigbuild
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-zigbuild
            ~/.cargo/bin/zigbuild
          key: cargo-zigbuild-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Enable Docker layer caching
          driver-opts: |
            image=moby/buildkit:buildx-stable-1

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Setup SSH key for AUR
        if: env.AUR_SSH_PRIVATE_KEY != ''
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        env:
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

      - name: Import GPG key
        if: env.GPG_PRIVATE_KEY != ''
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser.release.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
          TAG: ${{ needs.release-please.outputs.tag_name }}
          # Disable sccache for cross-compilation due to incompatibility with cargo-zigbuild
          # sccache doesn't support Zig's cross-compilation setup
          SCCACHE_GHA_ENABLED: "false"

      - name: Publish draft release
        if: success()
        run: |
          gh release edit ${{ needs.release-please.outputs.tag_name }} --draft=false
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          GH_REPO: ${{ github.repository }}
